### ISSUE TITLE
Multiple URLs or Script Support?

### ISSUE THREAD

**Issue by hjdhjd** [codetwice/homebridge-http-securitysystem#19]
Terrific, comprehensive plugin. Here's the ask...my use case involves the need to call MULTIPLE URLs for any arm / disarm event. To use this plugin, there are two ways I see to do this, and they both involve changing the existing functionality:

1. Add support for executing multiple URLs as part of each arm / disarm event...so when disarm is called, for instance, it would execute the URLs I specify, in order...

2. Add support for executing arbitrary scripts and returning exit status or stdout text (my preference being the latter) for each event.

Would you consider doing either (or both) of the above?

Thanks!

**Comment by codetwice** [comment]
Hi, I think both of the proposed solutions would work. I could make modifications to the handling of the config so that the URL blocks can not only be objects (with URL and body) but also arrays made up of object. This way you could have something like this in your config:

```
...
"urls": {
  "away": [
    { "url": "http://domain1/url1", "body": "away" },
    { "url": "http://domain2/url2", "body": "away" },
  ]
  ...
},
...
```

I think this would be sufficient for what you want to achieve. The second option (running a shell script) can also be done but I do not want to reach out of the scope of nodeJS unless really necessary as it may result in all sorts of new issues.

The only open question is what the behavior should be if there are multiple readCurrentState and readTargetState URLs... I cannot think of a realistic scenario where the current state data should be "assembled" in a way, especially that it's just a single number. Because of this, I think the multiple URL system will simply exclude those URLs, so array-like URL definitions will only work for the setters.

**Comment by codetwice** [comment]
I implemented the multi-URL support for the setters, as described above. The changes are on the develop branch, give it a spin and let me know how it went. If it's alright I'll merge it over to master.

**Comment by codetwice** [comment]
Removed it again as I did not like it so much. It was on for a while on the develop branch, if you need it back let me know.
